sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:

    - stage: Linux - Conan develop
      name: Python 2.7
      python: 2.7
      env: TOXENV=py27-conandev TOXARGS='-- --ignore=tests/test_hooks/conan-center/test_non_ascii_char.py'
    - name: Python 3.5
      python: 3.5
      env: TOXENV=py35-conandev
      dist: xenial
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-conandev
      dist: xenial

    # All Linux first, check versions
    - stage: Linux - Conan Current
      name: Python 2.7
      python: 2.7
      env: TOXENV=py27-conancurrent TOXARGS='-- --ignore=tests/test_hooks/conan-center/test_non_ascii_char.py'
    - name: Python 3.5
      python: 3.5
      env: TOXENV=py35-conancurrent
      dist: xenial
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-conancurrent
      dist: xenial

    - stage: Linux - Conan 1.24
      name: Python 3.5
      python: 3.5
      env: TOXENV=py35-conan124
      dist: xenial
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-conan124
      dist: xenial

    - stage: Linux - Conan 1.23
      name: Python 3.5
      python: 3.5
      env: TOXENV=py35-conan123
      dist: xenial
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-conan123
      dist: xenial

    # Macos is slow, only if everything has passed
    - stage: Macos - All Conan versions
      name: Conan develop - Python 3.8
      language: generic
      os: osx
      osx_image: xcode11.2
      env: PYVER=py38 TOXENV=py38-conandev
    - name: Conan Current - Python 2.7
      language: generic
      os: osx
      osx_image: xcode11.2
      env: PYVER=py27 TOXENV=py27-conancurrent TOXARGS='-- --ignore=tests/test_hooks/conan-center/test_non_ascii_char.py'
    - name: Conan Current - Python 3.5
      language: generic
      os: osx
      osx_image: xcode11.2
      env: PYVER=py35 TOXENV=py35-conancurrent
    - name: Conan Current - Python 3.8
      language: generic
      os: osx
      osx_image: xcode11.2
      env: PYVER=py38 TOXENV=py38-conancurrent

before_install:
  - ./.travis/before_install.sh

install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
      pyenv activate conan;
    fi
  - pip install --upgrade pip
  - |
    if [[ "$(pip freeze)" ]]; then
      pip uninstall -y -r <(pip freeze);
    fi
  - pip install -r .travis/requirements_travis.txt

script:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
      pyenv activate conan
    fi
  - tox ${TOXARGS}
