sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:

    - stage: Conan latest - Linux
      name: Conan latest - Linux - Python 3.7
      python: 3.7
      env: TOXENV=py37-conanlatest
      dist: xenial
      sudo: true
    - name: Conan latest - Linux - Python 2.7
      python: 2.7
      env: TOXENV=py27-conanlatest

    - stage: Conan develop - Linux
      name: Conan develop - Linux - Python 3.7
      python: 3.7
      env: TOXENV=py37-conandev
      dist: xenial
      sudo: true
    - name: Conan develop - Linux - Python 2.7
      python: 2.7
      env: TOXENV=py27-conandev

    # All Linux first, check versions
    - stage: Conan 1.12 - Linux
      python: 2.7
      env: TOXENV=py27-conan112
    - python: 3.4
      env: TOXENV=py34-conan112
    - python: 3.6
      env: TOXENV=py36-conan112
    - python: 3.7
      env: TOXENV=py37-conan112
      dist: xenial
      sudo: true

    - stage: Conan 1.11 - Linux
      python: 2.7
      env: TOXENV=py27-conan111
    - python: 3.4
      env: TOXENV=py34-conan111
    - python: 3.6
      env: TOXENV=py36-conan111
    - python: 3.7
      env: TOXENV=py37-conan111
      dist: xenial
      sudo: true

    - stage: Conan 1.10 - Linux
      python: 2.7
      env: TOXENV=py27-conan110
    - python: 3.4
      env: TOXENV=py34-conan110
    - python: 3.6
      env: TOXENV=py36-conan110
    - python: 3.7
      env: TOXENV=py37-conan110
      dist: xenial
      sudo: true

    # Macos is slow, only if everything has passed
    - stage: Macos - all Conan versions
      name: Conan develop - Mac - Python 3.7
      language: generic
      os: osx
      osx_image: xcode8.3
      env: PYVER=py37 TOXENV=py37-conandev

    - language: generic
      os: osx
      osx_image: xcode8.3
      env: PYVER=py27 TOXENV=py27-conan112
    - language: generic
      os: osx
      osx_image: xcode8.3
      env: PYVER=py37 TOXENV=py37-conan112

    - language: generic
      os: osx
      osx_image: xcode8.3
      env: PYVER=py27 TOXENV=py27-conan111
    - language: generic
      os: osx
      osx_image: xcode8.3
      env: PYVER=py37 TOXENV=py37-conan111

    - language: generic
      os: osx
      osx_image: xcode8.3
      env: PYVER=py27 TOXENV=py27-conan110
    - language: generic
      os: osx
      osx_image: xcode8.3
      env: PYVER=py37 TOXENV=py37-conan110

before_install:
  - ./.travis/before_install.sh

install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
      pyenv activate conan;
    fi
  - pip install --upgrade pip
  - pip install tox tox-venv
  - pip install -r .travis/requirements_travis.txt

script:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
      pyenv activate conan
    fi
  - tox
