build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        # Conan development
        - PYVER: py27
          TOXENV: py27-conandev
        - PYVER: py35
          TOXENV: py35-conandev
        - PYVER: py38
          TOXENV: py38-conandev

        # Conan current version
        - PYVER: py27
          TOXENV: py27-conancurrent
        - PYVER: py35
          TOXENV: py35-conancurrent
        - PYVER: py38
          TOXENV: py38-conancurrent

        # Conan prev 
        - PYVER: py38
          TOXENV: py38-conanprev

        # Conan prev prev
        - PYVER: py38
          TOXENV: py38-conanprevprev

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip install tox==3.7.0 tox-venv==0.3.1 requests

  - tox
