build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        # Conan development
        - PYVER: py27
          TOXENV: py27-conandev
        - PYVER: py35
          TOXENV: py35-conandev
        - PYVER: py38
          TOXENV: py38-conandev

        # Conan current version
        - PYVER: py27
          TOXENV: py27-conancurrent
        - PYVER: py35
          TOXENV: py35-conancurrent
        - PYVER: py38
          TOXENV: py38-conancurrent

        # Conan 1.23.x
        - PYVER: py38
          TOXENV: py38-conan123

        # Conan 1.22.x
        - PYVER: py38
          TOXENV: py38-conan122

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip install tox==3.7.0 tox-venv==0.3.1

test_script:
  - tox