build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        # Conan development
        - PYVER: py27
          TOXENV: py27-conandev
        - PYVER: py37
          TOXENV: py37-conandev
        - PYVER: py38
          TOXENV: py38-conandev

        # Conan current version
        - PYVER: py27
          TOXENV: py27-conancurrent
        - PYVER: py37
          TOXENV: py37-conancurrent
        - PYVER: py38
          TOXENV: py38-conancurrent

        # Conan 1.21.x
        - PYVER: py38
          TOXENV: py38-conan121

        # Conan 1.20.x
        - PYVER: py38
          TOXENV: py38-conan120

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip install tox==3.7.0 tox-venv==0.3.1

test_script:
  - tox