build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        # Conan development
        - PYVER: py27
          TOXENV: py27-conandev
        - PYVER: py37
          TOXENV: py37-conandev

        # Conan current version
        - PYVER: py27
          TOXENV: py27-conancurrent
        - PYVER: py36
          TOXENV: py36-conancurrent
        - PYVER: py37
          TOXENV: py37-conancurrent

        # Conan 1.12.x
        - PYVER: py27
          TOXENV: py27-conan112
        - PYVER: py36
          TOXENV: py36-conan112
        - PYVER: py37
          TOXENV: py37-conan112

        # Conan 1.11.x
        - PYVER: py27
          TOXENV: py27-conan111
        - PYVER: py36
          TOXENV: py36-conan111
        - PYVER: py37
          TOXENV: py37-conan111

        # Conan 1.10.x
        - PYVER: py27
          TOXENV: py27-conan110
        - PYVER: py36
          TOXENV: py36-conan110
        - PYVER: py37
          TOXENV: py37-conan110

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip install tox tox-venv

test_script:
  - tox