build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        # Conan development
        - PYVER: py27
          TOXENV: py27-conandev
        - PYVER: py37
          TOXENV: py37-conandev

        # Conan current version
        - PYVER: py27
          TOXENV: py27-conancurrent
        - PYVER: py36
          TOXENV: py36-conancurrent
        - PYVER: py37
          TOXENV: py37-conancurrent

        # Conan 1.18.x
        - PYVER: py27
          TOXENV: py27-conan118
        - PYVER: py36
          TOXENV: py36-conan118
        - PYVER: py37
          TOXENV: py37-conan118

        # Conan 1.17.x
        - PYVER: py27
          TOXENV: py27-conan117
        - PYVER: py36
          TOXENV: py36-conan117
        - PYVER: py37
          TOXENV: py37-conan117

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip install tox==3.7.0 tox-venv==0.3.1

test_script:
  - tox